spring:
  application:
    name: school
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:pgsql}
    driver-class-name: org.postgresql.Driver
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间


# mybatis
# mybatis:
#   mapper-locations: classpath:mapper/*.xml
#   type-aliases-package: com.gouggou.shardingtable.entity
#   configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# @Value( "${spring.application.name:#{null}}")
# private String name;