spring:   
  profiles:
    include: db
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      # - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cc.school.model
  configuration:
    map-underscore-to-camel-case: true
